### ISSUE TITLE
I Have No Clue On How To Launch The Game Pls Help Me :(

### ISSUE THREAD

**Issue by Cyper321** [shylor/miniventure#16]

**Comment by shylor** [comment]
Do you have Java installed? You should be able to just double tap the .jar file and run it.

**Comment by MidnightStar88** [comment]
hi i am running windows 10 and have the most recent java installed,i have clicked on the download jar file on playminicraft.com but cant seem to open or load the game :( is there anything else i need to do?? im not sure how to use java to open the jar file.... please help im dying to play this game ;) Ashley
![2017-02-17](https://cloud.githubusercontent.com/assets/25719040/23053829/e8a44310-f4d3-11e6-8a1c-0d8b98f3f503.png)

**Comment by shylor** [comment]
Try right-clicking the jar file and "open as" java. If that is not an open download java. https://java.com

**Comment by MidnightStar88** [comment]
i already have java installed..... here is a picture of when i right click it and go to open with,none of these work i dont think i have the right java file in there to open it...which do i select?? 
![2017-02-17 3](https://cloud.githubusercontent.com/assets/25719040/23054036/5709fa74-f4d5-11e6-90b6-c6b5ff137000.png)

**Comment by MidnightStar88** [comment]
this is where i select while program i want to open jar files ... what am i supposed to use...what shud it be called? because i cant get any working :(
![2017-02-17 4](https://cloud.githubusercontent.com/assets/25719040/23054258/afef6bf0-f4d6-11e6-9fab-ed334aefc934.png)

**Comment by shylor** [comment]
See if you have this? 
![image](https://cloud.githubusercontent.com/assets/1676257/23054360/707b0c64-f4ad-11e6-8184-872422ff5290.png)

**Comment by MidnightStar88** [comment]
ok ive done that but when i click the jar file a black window opens for like 1 second then it dissapears again :( why aint it loading? do i need to have github installed too? 
![2017-02-17 5](https://cloud.githubusercontent.com/assets/25719040/23055128/fff41b8c-f4db-11e6-8fcc-8355d1dbe857.png)

**Comment by MidnightStar88** [comment]
please help ,,,

**Comment by shylor** [comment]
Try installing Java 64 bit. I think that might fix it. If it does confirm that here.

**Comment by gdavid04** [comment]
just open the jar file

**Comment by BoyBlueSky** [comment]
This is a common problem, and here is one solution:
http://projects.killerapplets.com/JAR_Runner/

From the CNet download page:
From KillerApplets.com:
In earlier versions of Windows & by default, JAR files were opened & run by the current Java installation.  Somewhere along the way however, this file association can be broken.  For example, WinRAR (a popular compression/extraction utility) may be defaulted to open the JAR files as compressed archives - allowing one to view the contained files but providing no means by which to run them.  Also, later versions of Windows (currently, such as Windows 10) simply do not have JAR files associated with the current Java installation for whatever reason.  So, users upgrading to 10 may suddenly find such programs are no longer loading.  Yet, rest assured!  The program likely still works! ...It just needs a little help loading.

Now certainly, the JAR file still needs Java to run.  Yet if a user does not happen to know either the command-line syntax or where the necessary files are, this already poses a bit of a problem - especially since the folder in which Java is located is not always the same but often times reflects the specific version of that particular Java installation.  Luckily, Java's folder is most often added automatically to the default system path, and this helps us find where it is.  Even if one knows how to do all this, it can be a bit of a hassle to do each time one wishes to load a JAR application.

JAR_Runner locates the current Java installation, calls the appropriate application (JavaW.exe), & directs it to run the JAR file.  It integrates right into the Windows system & also has a CMD/DOS command line option.

**Comment by BoyBlueSky** [comment]
http://projects.killerapplets.com/JAR_Runner/

Sometimes, the this file association can be broken, and Windows users may suddenly find such programs are no longer loading. Yet, rest assured! The program likely still works! ...It just needs a little help loading.

JAR_Runner locates the current Java installation, calls the appropriate application (JavaW.exe), & directs it to run the JAR file. It integrates right into the Windows system & also has a CMD/DOS command line option.

Options:
- Click-&-drag JAR file onto the JAR_Runner EXEcutable or shortcut
- Right-click JAR file, select "Open with", navigate to JAR_Runner EXEcutable
. . (Of course, one can make this the default for JAR files from now on)
- Command line syntax: JAR_RUNNER [drive:][path]filename
